import { GoogleGenAI } from "@google/genai";

console.log("VITE_BASE_URL:", import.meta.env.VITE_BASE_URL); // Debug log to check if the base URL is loaded
console.log("GEMINI_API_KEY:", import.meta.env.GEMINI_API_KEY); // Debug log to check if the API key is loaded

const ai = new GoogleGenAI({ apiKey: import.meta.env.GEMINI_API_KEY });

export async function transformImage(
  base64Image: string,
  config: {
    standName: string;
    muscularity: number;
    sharpness: number;
  }
) {
  // We use gemini-2.5-flash-image for transformation (editing)
  // or gemini-3.1-flash-image-preview for high quality.
  // Using 3.1 for high quality as requested.
  
  const prompt = `Transform this person into an iconic "JoJo's Bizarre Adventure" character. 
  Style Requirements:
  1. Muscular proportions: Level ${config.muscularity}/10 (extreme peak human physique).
  2. Sharp facial features: Strong jawline, high cheekbones, intense eyes with heavy lashes/mascara-like lines.
  3. Bold Cel-Shaded coloring: High contrast, thick black ink outlines, vibrant color palette.
  4. Manga Details: Add speed lines, hatching for shadows, and stylized cross-hatching.
  5. Pose: Make the person strike a dramatic, over-the-top "JoJo Pose".
  6. Concept: This character's Stand is called "${config.standName}".
  7. High resolution, anime aesthetic, Hirohiko Araki style.
  
  Ensure the identity of the person is recognizable but heavily stylized.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          { inlineData: { data: base64Image.split(',')[1] || base64Image, mimeType: "image/jpeg" } },
          { text: prompt },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "3:4",
          imageSize: "1K"
        }
      }
    });

    const parts = response?.candidates?.[0]?.content?.parts;
    if (!parts) {
      throw new Error("No image generated by model");
    }

    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by model");
  } catch (error) {
    console.error("Transformation Error:", error);
    throw error;
  }
}
