import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const teams = [
  { rank: 1, id: 'cw', name: 'Curaçao', code: 'cw', color: '#002B7F' },
  { rank: 2, id: 'ht', name: 'Haiti', code: 'ht', color: '#00209F' },
  { rank: 3, id: 'nz', name: 'New Zealand', code: 'nz', color: '#000000' },
  { rank: 4, id: 'uz', name: 'Uzbekistan', code: 'uz', color: '#00A3E0' },
  { rank: 5, id: 'jo', name: 'Jordan', code: 'jo', color: '#1D70B8' },
  { rank: 6, id: 'cv', name: 'Cabo Verde', code: 'cv', color: '#002B7F' },
  { rank: 7, id: 'cd', name: 'Congo DR', code: 'cd', color: '#007FFF' },
  { rank: 8, id: 'iq', name: 'Iraq', code: 'iq', color: '#007A3D' },
  { rank: 9, id: 'za', name: 'South Africa', code: 'za', color: '#007A3D' },
  { rank: 10, id: 'ba', name: 'Bosnia & Herz.', code: 'ba', color: '#002F6C' },
  { rank: 11, id: 'qa', name: 'Qatar', code: 'qa', color: '#8A1538' },
  { rank: 12, id: 'pa', name: 'Panama', code: 'pa', color: '#DA1A32' },
  { rank: 13, id: 'sa', name: 'Saudi Arabia', code: 'sa', color: '#006C35' },
  { rank: 14, id: 'gh', name: 'Ghana', code: 'gh', color: '#FCD116' },
  { rank: 15, id: 'tn', name: 'Tunisia', code: 'tn', color: '#E70013' },
  { rank: 16, id: 'no', name: 'Norway', code: 'no', color: '#EF2B2D' },
  { rank: 17, id: 'gb-sct', name: 'Scotland', code: 'gb-sct', color: '#005EB8' },
  { rank: 18, id: 'cz', name: 'Czechia', code: 'cz', color: '#11457E' },
  { rank: 19, id: 'eg', name: 'Egypt', code: 'eg', color: '#C0930C' },
  { rank: 20, id: 'dz', name: 'Algeria', code: 'dz', color: '#006233' },
  { rank: 21, id: 'ci', name: 'Côte d\'Ivoire', code: 'ci', color: '#FF8200' },
  { rank: 22, id: 'ir', name: 'IR Iran', code: 'ir', color: '#239E46' },
  { rank: 23, id: 'tr', name: 'Türkiye', code: 'tr', color: '#E30A17' },
  { rank: 24, id: 'se', name: 'Sweden', code: 'se', color: '#006AA7' },
  { rank: 25, id: 'py', name: 'Paraguay', code: 'py', color: '#D52B1E' },
  { rank: 26, id: 'au', name: 'Australia', code: 'au', color: '#00008B' },
  { rank: 27, id: 'kr', name: 'Korea Republic', code: 'kr', color: '#CD2E3A' },
  { rank: 28, id: 'at', name: 'Austria', code: 'at', color: '#ED2939' },
  { rank: 29, id: 'ec', name: 'Ecuador', code: 'ec', color: '#FFCC00' },
  { rank: 30, id: 'ca', name: 'Canada', code: 'ca', color: '#FF0000' },
  { rank: 31, id: 'sn', name: 'Senegal', code: 'sn', color: '#11A335' },
  { rank: 32, id: 'mx', name: 'Mexico', code: 'mx', color: '#006847' },
  { rank: 33, id: 'us', name: 'USA', code: 'us', color: '#002868' },
  { rank: 34, id: 'co', name: 'Colombia', code: 'co', color: '#FCD116' },
  { rank: 35, id: 'ch', name: 'Switzerland', code: 'ch', color: '#D52B1E' },
  { rank: 36, id: 'jp', name: 'Japan', code: 'jp', color: '#00008B' },
  { rank: 37, id: 'ma', name: 'Morocco', code: 'ma', color: '#C1272D' },
  { rank: 38, id: 'uy', name: 'Uruguay', code: 'uy', color: '#0081C8' },
  { rank: 39, id: 'hr', name: 'Croatia', code: 'hr', color: '#FF0000' },
  { rank: 40, id: 'be', name: 'Belgium', code: 'be', color: '#E30613' },
  { rank: 41, id: 'de', name: 'Germany', code: 'de', color: '#FFCC00' },
  { rank: 42, id: 'nl', name: 'Netherlands', code: 'nl', color: '#21468B' },
  { rank: 43, id: 'pt', name: 'Portugal', code: 'pt', color: '#FF0000' },
  { rank: 44, id: 'gb-eng', name: 'England', code: 'gb-eng', color: '#E21B2C' },
  { rank: 45, id: 'es', name: 'Spain', code: 'es', color: '#C60B1E' },
  { rank: 46, id: 'fr', name: 'France', code: 'fr', color: '#002395' },
  { rank: 47, id: 'br', name: 'Brazil', code: 'br', color: '#009739' },
  { rank: 48, id: 'ar', name: 'Argentina', code: 'ar', color: '#75AADB' }
];

const flagsDir = path.join(__dirname, '../public/flags');
if (!fs.existsSync(flagsDir)) {
  fs.mkdirSync(flagsDir, { recursive: true });
}

// Generate TS definitions file
const teamsTsPath = path.join(__dirname, '../src/app/teams.ts');
const tsContent = `// Auto-generated by scripts/download-flags.mjs
export interface Team {
  rank: number; // 1 (smallest) to 48 (largest)
  id: string;
  name: string;
  code: string;
  color: string;
}

export const TEAMS: Team[] = ${JSON.stringify(teams, null, 2)};
`;

fs.writeFileSync(teamsTsPath, tsContent);
console.log(`Wrote teams metadata to ${teamsTsPath}`);

// Download all flags
console.log('Downloading flags...');
async function downloadFlags() {
  for (const team of teams) {
    const dest = path.join(flagsDir, `${team.code}.png`);
    if (fs.existsSync(dest)) {
      console.log(`Flag for ${team.name} already exists. Skipping.`);
      continue;
    }

    const url = `https://flagcdn.com/w160/${team.code}.png`;
    try {
      console.log(`Downloading flag for ${team.name} (${team.code}) from ${url}...`);
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      fs.writeFileSync(dest, buffer);
    } catch (error) {
      console.error(`Failed to download flag for ${team.name}:`, error);
    }
    // Sleep a bit to avoid hitting rate limits
    await new Promise((resolve) => setTimeout(resolve, 150));
  }
  console.log('All flag downloads completed.');
}

downloadFlags();
