import { GoogleGenAI } from "@google/genai";
import { errorResponse, jsonResponse } from "../http/json.ts";

type TransformPayload = {
  base64Image: string;
  standName: string;
  muscularity: number;
  sharpness: number;
};

type TransformConfig = {
  geminiApiKey: string;
  origin: string;
};

export async function transform(request: Request, config: TransformConfig): Promise<Response> {
  if (!config.geminiApiKey) {
    return errorResponse("GEMINI_API_KEY is not configured", 500, config.origin);
  }

  const payload = await readPayload(request);
  const validationError = validatePayload(payload);
  if (validationError) {
    return errorResponse(validationError, 400, config.origin);
  }

  const result = await transformImage(payload, config.geminiApiKey);
  return jsonResponse({ image: result }, { status: 200 }, config.origin);
}

async function readPayload(request: Request): Promise<TransformPayload> {
  try {
    return await request.json();
  } catch {
    throw new BadRequestError("Request body must be valid JSON");
  }
}

function validatePayload(payload: TransformPayload): string | null {
  if (!payload || typeof payload !== "object") {
    return "Request body is required";
  }

  if (typeof payload.base64Image !== "string" || payload.base64Image.length === 0) {
    return "base64Image is required";
  }

  if (typeof payload.standName !== "string" || payload.standName.trim().length === 0) {
    return "standName is required";
  }

  if (!isScaleValue(payload.muscularity)) {
    return "muscularity must be a number from 1 to 10";
  }

  if (!isScaleValue(payload.sharpness)) {
    return "sharpness must be a number from 1 to 10";
  }

  return null;
}

function isScaleValue(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value >= 1 && value <= 10;
}

async function transformImage(payload: TransformPayload, apiKey: string): Promise<string> {
  const ai = new GoogleGenAI({ apiKey });
  const image = parseBase64Image(payload.base64Image);

  const prompt = `Transform this person into an iconic "JoJo's Bizarre Adventure" character.
Style Requirements:
1. Muscular proportions: Level ${payload.muscularity}/10.
2. Sharp facial features: Level ${payload.sharpness}/10, strong jawline, high cheekbones, intense eyes.
3. Bold cel-shaded coloring with high contrast, thick black ink outlines, and a vibrant palette.
4. Manga details: speed lines, hatching for shadows, and stylized cross-hatching.
5. Pose: make the person strike a dramatic, over-the-top JoJo pose.
6. Concept: this character's Stand is called "${payload.standName}".
7. High resolution anime aesthetic.

Ensure the identity of the person is recognizable but heavily stylized.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.1-flash-image-preview",
    contents: {
      parts: [
        { inlineData: { data: image.data, mimeType: image.mimeType } },
        { text: prompt },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "3:4",
        imageSize: "1K",
      },
    },
  });

  const parts = response?.candidates?.[0]?.content?.parts;
  const generatedImage = parts?.find((part) => part.inlineData)?.inlineData?.data;

  if (!generatedImage) {
    throw new Error("No image generated by model");
  }

  return `data:image/png;base64,${generatedImage}`;
}

function parseBase64Image(base64Image: string): { data: string; mimeType: string } {
  const match = base64Image.match(/^data:(?<mimeType>[-\w/+]+);base64,(?<data>.+)$/);
  if (!match?.groups) {
    return {
      data: base64Image,
      mimeType: "image/jpeg",
    };
  }

  return {
    data: match.groups.data,
    mimeType: match.groups.mimeType,
  };
}

export class BadRequestError extends Error {}
